############ This image is built for Raspberry Pi (arm64-v8) ############ 

# set base image (host OS)
# FROM python:3.8 as emotion_recognition
#FROM jasonrandrews/tensorflow-v2 as emotion_recognition-docker-arm
#FROM mantika/tensorflow:2.4-arm64-wheels as emotion_recognition-docker
FROM hwkypgils/tensorflow:32.5.1-tf2.4-py3.6-t210-11e7fa6 as emotion_recognition-docker-arm
# set the working directory in the container
WORKDIR /



RUN apt update
RUN apt install python3-pip -y
RUN apt-get install ffmpeg libsm6 libxext6  -y


RUN pip3 install --upgrade pip
# install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# copy all files from the local directory to the working directory
COPY *.* /
#RUN pip install tensorflow-2.4.1-cp37-cp37m-manylinux2010_x86_64.whl
#RUN rm tensorflow-2.4.1-cp37-cp37m-manylinux2010_x86_64.whl

# copy the content of all directories to the working directory while keeping the path
COPY emojis /emojis/
COPY haarcascades /haarcascades/
COPY media /media/
COPY models /models/
COPY save_loc /save_loc/
COPY saved_images /saved_images/

# command to run on container start
ENTRYPOINT ["python","__init__.py"]

